-- DROP TABLE IF EXISTS stg_borrower;
-- CREATE TABLE "stg_borrower" ("borrower_id" VARCHAR(36), "full_name" VARCHAR(50), "street" VARCHAR(100), "city" VARCHAR(100), "state" VARCHAR(50), "zip_code" VARCHAR(15), "phone_home" VARCHAR(12), "phone_cell" VARCHAR(12), email VARCHAR(128));
-- DROP TABLE IF EXISTS stg_role_profile;
-- CREATE TABLE "stg_role_profile" ("borrower_id" VARCHAR(36), "role_profile" VARCHAR(15));
DROP TABLE IF EXISTS user_profile;
CREATE TABLE "user_profile" ("user_id" SERIAL PRIMARY KEY,borrower_id varchar(36) NOT NULL, "first_name" VARCHAR(128) NOT NULL, "last_name" VARCHAR(128) NOT NULL, "created_date" timestamp default CURRENT_TIMESTAMP NOT NULL, "created_by" VARCHAR(128) NOT NULL, "updated_date" timestamp, "updated_by" VARCHAR(128));
DROP TABLE IF EXISTS role_profile;
CREATE TABLE "role_profile" ("role_profile_id" SERIAL PRIMARY KEY,"user_id" INTEGER,"role_profile_type_id" INTEGER,"created" timestamp default CURRENT_TIMESTAMP NOT NULL,"created_by" VARCHAR(128) NOT NULL,"updated" timestamp,"updated_by" VARCHAR(128), CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES user_profile(user_id), CONSTRAINT fk_role_profile_type_id FOREIGN KEY(role_profile_type_id) REFERENCES role_profile_type(role_profile_type_id));
DROP TABLE IF EXISTS role_profile_type;
CREATE TABLE "role_profile_type" ("role_profile_type_id" SERIAL PRIMARY KEY,"type" VARCHAR(128),"created" timestamp default CURRENT_TIMESTAMP NOT NULL,"created_by" VARCHAR(128) NOT NULL,"updated" timestamp,"updated_by" VARCHAR(128));
DROP TABLE IF EXISTS email;
CREATE TABLE "email" ("email_id" SERIAL PRIMARY KEY,"role_profile_id" INT, "email_type_id" INT, "value" VARCHAR(50) NOT NULL,"created" timestamp default CURRENT_TIMESTAMP NOT NULL,"created_by" VARCHAR(128) NOT NULL,"updated" timestamp,"updated_by" VARCHAR(128), CONSTRAINT fk_role_profile_id FOREIGN KEY(role_profile_id) REFERENCES role_profile(role_profile_id), CONSTRAINT fk_email_type_id FOREIGN KEY(email_type_id) REFERENCES email_type(email_type_id));
DROP TABLE IF EXISTS email_type;
CREATE TABLE "email_type" ("email_type_id" SERIAL PRIMARY KEY,"type" VARCHAR(128),"created" timestamp default CURRENT_TIMESTAMP NOT NULL,"created_by" VARCHAR(128) NOT NULL,"updated" timestamp,"updated_by" VARCHAR(128));
DROP TABLE IF EXISTS address;
CREATE TABLE "address" ("address_id" SERIAL PRIMARY KEY,"role_profile_id" INT,"street" VARCHAR(128),"city" VARCHAR(128) NOT NULL,"state" VARCHAR(64) NOT NULL,"zip_code" VARCHAR(32) NOT NULL,"created" timestamp default CURRENT_TIMESTAMP NOT NULL,"created_by" VARCHAR(128) NOT NULL,"updated" timestamp,"updated_by" VARCHAR(128), CONSTRAINT fk_role_profile_id FOREIGN KEY(role_profile_id) REFERENCES role_profile(role_profile_id));
DROP TABLE IF EXISTS phone_number;
CREATE TABLE "phone_number" ("phone_number_id" SERIAL PRIMARY KEY, "role_profile_id" INT,"phone_number_type_id" INT,"value" VARCHAR(20) NOT NULL,"created" timestamp default CURRENT_TIMESTAMP NOT NULL,"created_by" VARCHAR(128) NOT NULL,"updated" timestamp,"updated_by" VARCHAR(128), CONSTRAINT fk_phone_number_type FOREIGN KEY(phone_number_type_id) REFERENCES phone_number_type(phone_number_type_id), CONSTRAINT fk_role_profile FOREIGN KEY(role_profile_id) REFERENCES role_profile(role_profile_id));
DROP TABLE IF EXISTS phone_number_type;
CREATE TABLE "phone_number_type" ("phone_number_type_id" SERIAL PRIMARY KEY,"type" VARCHAR(128) NOT NULL,"created" timestamp default CURRENT_TIMESTAMP NOT NULL,"created_by" VARCHAR(128) NOT NULL,"updated" timestamp,"updated_by" VARCHAR(128));